catalog/urls.py
"""Catolog URLs."""

from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path('', views.check_data, name='check_data'),
    path('list/', views.mineral_list, name='list'),
    path('list/letter/<name_filter>', views.mineral_list, name='filtered_list'),
    path('list/group/<group_filter>', views.mineral_group, name='group_list'),
    path('list/streak/<streak_filter>', views.mineral_streak, name='streak_list'),
    path('detail/<int:pk>/', views.mineral_detail, name='detail'),
    path('import/', views.import_minerals, name='import'),
    path('search/', views.search, name='search'),
]

project_06/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
]

project_08/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from rest_framework import routers

from catalog import api_views

router = routers.SimpleRouter()
router.register(r'minerals', api_views.MineralViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('catalog.urls')),
    path("api/v1/", include((router.urls, 'minerals'), namespace="apiv1")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
       path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/home.html
<h1>Holding page</h1>
<p>not used</p>

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <title>Martha's Minerals: A magnificant catalog of minerals</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/catalog-style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

{% if not import %}
    <section class="filters">

    <h2 class="cat-title">Groups</h2>
    <ul class="group-list">
        {% for group in groups %}
            <li class="group-label {% if search_term == group.0 %}active{% endif %}">
                <a href="{% url 'catalog:group_list' group_filter=group.1 %}">{{ group.0 }}</a>
            </li>
        {% endfor %}
    </ul>
    </section>
<section class="filters">
    <h2 class="cat-title">Streak</h2>
    <ul class="group-list">
    {% for streak in streaks %}
            <li class="group-label {% if search_term == streak.0 %}active{% endif %}">
                <a href="{% url 'catalog:streak_list' streak_filter=streak.1 %}">{{ streak.0 }}</a>
            </li>
        {% endfor %}
        </ul>
    </section>

{% endif %}


{% block boundsClass %}{% endblock %}

<div class=" grid-100">
<a href="{% url 'catalog:list' %}">
    <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
        <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
        <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
        <polygon
                points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
    </svg>
    <h1 class="logo__name text-centered">Martha's Minerals</h1>
</a>
<p class="logo__text text-centered">So much more than rocks.</p>
</div>

{% if not import %}

    {% for letter in 'abcdefghijklmnopqrstuvwxyz' %}
        <section
                class="search-area {% if request.resolver_match.route == 'detail/<int:pk>/' %}search-detail{% endif %}">
            <ul>
                {% if letter == 'a' %}
                    <li class="letters
                {% if name_filter == 'a' or not request.resolver_match.kwargs and request.resolver_match.url_name != 'search' %}
                active{% endif %}"><a href="{% url 'catalog:filtered_list' name_filter='a' %}">A</a></li>
                {% else %}
                    <li class="letters {% if name_filter == letter %}active{% endif %}">
                        <a href="{% url 'catalog:filtered_list' name_filter=letter %}">{{ letter|upper }}</a></li>
                {% endif %}
            </ul>
        </section>
    {% endfor %}
    <section class="search-bar">
        <div class="search-container {% if request.resolver_match.route == 'detail/<int:pk>/' %}search-detail{% endif %}">
            <form action="{% url 'catalog:search' %}" method="GET">
                <input type="text" placeholder="Search.." name="q">
                <button type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div>
    </section>

{% endif %}
{% block content %}{% endblock %}
</div>

{% if not import %}
    <div class="minerals__random">
        <a class="minerals__anchor shift" href="{% url 'catalog:detail' pk=random_mineral %}">Show random mineral</a>
    </div>
{% endif %}
</body>
</html>