catalog/urls.py
"""Catolog URLs."""

from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path('', views.check_data, name='check_data'),
    path('list/', views.mineral_list, name='list'),
    path('list/letter/<name_filter>', views.mineral_list, name='filtered_list'),
    path('list/group/<group_filter>', views.mineral_group, name='group_list'),
    path('list/streak/<streak_filter>', views.mineral_streak, name='streak_list'),
    path('detail/<int:pk>/', views.mineral_detail, name='detail'),
    path('import/', views.import_minerals, name='import'),
    path('search/', views.search, name='search'),
]

project_06/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
]

project_08/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from rest_framework import routers

from catalog import api_views

router = routers.SimpleRouter()
router.register(r'minerals', api_views.MineralViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('catalog.urls')),
    path("api/v1/", include((router.urls, 'minerals'), namespace="apiv1")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
       path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

catalog/models.py
"""Catalog Models."""
from django.db import models


class Mineral(models.Model):
    """Define the Mineral model."""

    name = models.CharField(max_length=255, unique=True)
    image_filename = models.CharField(max_length=255)
    image_caption = models.TextField()
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    strunz_classification = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    crystal_system = models.CharField(max_length=255)
    unit_cell = models.CharField(max_length=255)
    crystal_symmetry = models.CharField(max_length=255)
    cleavage = models.CharField(max_length=255)
    mohs_scale_hardness = models.CharField(max_length=255)
    luster = models.CharField(max_length=255)
    streak = models.CharField(max_length=255)
    diaphaneity = models.CharField(max_length=255)
    optical_properties = models.CharField(max_length=255)
    refractive_index = models.CharField(max_length=255)
    crystal_habit = models.CharField(max_length=255)
    specific_gravity = models.CharField(max_length=255)
    group = models.CharField(max_length=255)

    def __str__(self):
        """Define the str."""
        return self.name

    class Meta:
        """Define the ordering."""

        ordering = ['name']

    def get_fields(self, ordered_fields):
        """Returns a list with a dictionary of all field names on the instance."""
        field_list = []
        for field in ordered_fields:
            field_list.append(
                {field[0]: getattr(self, field[0])}
            )
        return field_list

    @classmethod
    def add_mineral(cls, minerals):
        """Add the data."""
        duplicates = 0
        for mineral in minerals:
            try:
                cls.objects.get(name=mineral.get('name', ''))
                duplicates += 1
            except cls.DoesNotExist:
                obj = cls(
                    name=mineral.get('name', ''),
                    image_filename=mineral.get('image_filename', ''),
                    image_caption=mineral.get('image_caption', ''),
                    category=mineral.get('category', ''),
                    formula=mineral.get('formula', ''),
                    strunz_classification=mineral.get('strunz_classification', ''),
                    color=mineral.get('color', ''),
                    crystal_system=mineral.get('crystal_system', ''),
                    unit_cell=mineral.get('unit_cell', ''),
                    crystal_symmetry=mineral.get('crystal_symmetry', ''),
                    cleavage=mineral.get('cleavage', ''),
                    mohs_scale_hardness=mineral.get('mohs_scale_hardness', ''),
                    luster=mineral.get('luster', ''),
                    streak=mineral.get('streak', ''),
                    diaphaneity=mineral.get('diaphaneity', ''),
                    optical_properties=mineral.get('optical_properties', ''),
                    refractive_index=mineral.get('refractive_index', ''),
                    crystal_habit=mineral.get('crystal_habit', ''),
                    specific_gravity=mineral.get('specific_gravity', ''),
                    group=mineral.get('group', ''),
                )
                obj.save()
        return duplicates

catalog/views.py
"""Catalog Views."""
import random
import os

from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from . import utils
from .models import Mineral

DATA_SOURCE = os.path.join(os.getcwd(), 'catalog/data/minerals.json')
# DATA_SOURCE = os.path.join(os.getcwd(), 'catalog/data/test.json')


def check_data(request):
    """Check if the database contains data and redirect accordingly."""
    minerals = Mineral.objects.all().order_by('id')
    if minerals:
        return HttpResponseRedirect('/list')
    else:
        return render(request, 'catalog/no-data.html', {'import': True, })


def import_minerals(request):
    """Import all minerals from JSON to DB."""
    data = utils.get_data(DATA_SOURCE)
    minerals_json_count = data['minerals_json_count']
    duplicate_count = data['duplicate_count']
    minerals = Mineral.objects.all().order_by('id')
    ordered_fields = utils.get_popular(request)
    return render(request, 'catalog/import.html',
                  {'import': True,
                   'minerals_json_count': minerals_json_count,
                   'duplicate_count': duplicate_count,
                   'minerals': minerals,
                   'ordered_fields': ordered_fields})


def mineral_list(request, name_filter='a'):
    """Mineral list view."""
    mineral_filtered = Mineral.objects.filter(name__istartswith=name_filter).order_by('id')
    num_in_list = mineral_filtered.count()
    random_mineral = random.choice(utils.get_ids())
    return render(request, 'catalog/list.html', {
        'name_filter': name_filter,
        'mineral_filtered': mineral_filtered,
        'num_in_list': num_in_list,
        'groups': utils.get_groups(request),
        'streaks': utils.get_streaks(request),
        'random_mineral': random_mineral,
    })


def mineral_group(request, group_filter):
    """Mineral Group view."""
    random_mineral = random.choice(utils.get_ids())
    groups = utils.get_groups(request)
    search_term = [item[0] for item in groups if group_filter in item][0]  # Get the de-slugified search term
    mineral_filtered = Mineral.objects.filter(group__iexact=search_term).order_by('id')
    num_in_group = mineral_filtered.count()
    return render(request, 'catalog/list.html', {
        'search_term': search_term,
        'mineral_filtered': mineral_filtered,
        'groups': groups,
        'streaks': utils.get_streaks(request),
        'num_in_group': num_in_group,
        'random_mineral': random_mineral,
    })


def mineral_streak(request, streak_filter):
    """Mineral Streak view."""
    random_mineral = random.choice(utils.get_ids())
    streaks = utils.get_streaks(request)
    search_term = [item[0] for item in streaks if streak_filter in item][0]  # Get the de-slugified search term
    mineral_filtered = Mineral.objects.filter(streak__iexact=search_term).order_by('id')
    num_in_group = mineral_filtered.count()
    return render(request, 'catalog/list.html', {
        'search_term': search_term,
        'mineral_filtered': mineral_filtered,
        'groups': utils.get_groups(request),
        'streaks': streaks,
        'num_in_group': num_in_group,
        'random_mineral': random_mineral,
    })


def mineral_detail(request, pk):
    """Mineral detail view."""
    random_mineral = random.choice(utils.get_ids())
    mineral = get_object_or_404(Mineral, pk=pk)
    ordered_fields = utils.get_popular(request)
    field_list = mineral.get_fields(ordered_fields)
    return render(request, 'catalog/detail.html', {
                'mineral': mineral,
                'field_list': field_list,
                'groups': utils.get_groups(request),
                'streaks': utils.get_streaks(request),
                'random_mineral': random_mineral,
    })


def search(request):
    """Search view. Perform a keyword search across all fields."""
    random_mineral = random.choice(utils.get_ids())
    term = request.GET.get('q')
    mineral_filtered = Mineral.objects.filter(
        Q(name__icontains=term) |
        Q(image_filename__icontains=term) |
        Q(image_caption__icontains=term) |
        Q(category__icontains=term) |
        Q(formula__icontains=term) |
        Q(strunz_classification__icontains=term) |
        Q(color__icontains=term) |
        Q(crystal_system__icontains=term) |
        Q(unit_cell__icontains=term) |
        Q(crystal_symmetry__icontains=term) |
        Q(cleavage__icontains=term) |
        Q(mohs_scale_hardness__icontains=term) |
        Q(luster__icontains=term) |
        Q(streak__icontains=term) |
        Q(diaphaneity__icontains=term) |
        Q(optical_properties__icontains=term) |
        Q(refractive_index__icontains=term) |
        Q(crystal_habit__icontains=term) |
        Q(specific_gravity__icontains=term) |
        Q(group__icontains=term)
    )
    num_results = mineral_filtered.count()
    return render(request, 'catalog/list.html', {
        'mineral_filtered': mineral_filtered,
        'num_results': num_results,
        'term': term,
        'groups': utils.get_groups(request),
        'streaks': utils.get_streaks(request),
        'random_mineral': random_mineral,
    })

catalog/templates/catalog/detail.html
{% extends 'layout.html' %}
{% load catalog_extras %}
{% load static %}

{% block boundsClass %}
    <div class="bounds bounds--small">{% endblock %}

{% block content %}
    <div class="grid-100 mineral__container">
        <h1 class="mineral__name hero">{{ mineral.name }}</h1>
        <div class="mineral__image-bg">
            <img class="mineral__image" src="{% static 'images/' %}{{ mineral.image_filename }}">
            {% if mineral.image_caption %}
                <p class="mineral__caption caption_highlight">{{ mineral.image_caption|safe }}</p>
            {% endif %}
        </div>
        <div class="mineral__table-container">
            <table class="mineral__table">
                {% for field in field_list %}
                    {% for name, content in field.items %}
                        {% if content %}
                            <tr {% if 'group' in name %}class="group-highlight"{% endif %}>
                                <td class="mineral__category">
                                    {{ name|safe|underscore_to_space|title }}
                                </td>
                                <td>
                                    {{ content|safe }}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/impoer_result.html
{% extends 'layout.html' %}
{% load catalog_extras %}

{% block boundsClass %}
    <div class="bounds bounds--small">
{% endblock %}

{% block content %}
    This is the Catalog IMPORT RESULT page.
    <br>
    <hr><br>
    <p>There are {% item_count minerals_json %} records in total.</p>
    <ol>
        {% for mineral in minerals_json %}
            <li>{{ mineral.name }}</li>
        {% endfor %}
    </ol>
{% endblock %}

catalog/templates/catalog/import.html
{% extends 'layout.html' %}
{% load catalog_extras %}

{% block boundsClass %}
    <div class="bounds bounds--small">
{% endblock %}

{% block content %}
    <div class="grid-100 mineral__container">
        <h1 class="mineral__name">Import result</h1>
        <p>{{ minerals_json_count }} records retrieved from 'minerals.json'. <br>
            {% import_report minerals_json_count duplicate_count %}</p>

        <br>
        <h2>Status</h2>
        <p>{{ minerals.count }} records in Martha's Minerals database.<br>
            <a class="b-link" href="{% url 'catalog:list' %}">Click to continue</a></p>
        <hr>
        <h3 class="mineral__name">Field popularity / occurrence count</h3>
        <p>Listed below are all the fields included in the dataset,
            together with the number of times that they are used.</p>
        <div class="mineral__table-container">
            <table class="mineral__table">
                {% for field in ordered_fields %}
                    <tr>
                        <td class="mineral__category">{{ field.0|safe|underscore_to_space|title }}</td>
                        <td class="text-centered">{{ field.1 }}</td>
                    </tr>
                {% endfor %}
            </table>
            <br>
            <p><a class="b-link" href="{% url 'catalog:list' %}">Click to continue</a></p>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'layout.html' %}

{% block boundsClass %}
    <div class="bounds">{% endblock %}
{% block importLink %}
    <div class="import">
        <a class="minerals__anchor import_button" href="{% url 'catalog:import' %}">Import data</a>
    </div>
{% endblock %}
{% block content %}
    <div class="grid-100">
            {% if not mineral_filtered %}
                <div class="info__container info_results">
                    <h2>No results found {% if term %}for '{{ term }}'{% endif %}</h2>
                    <p>Please try another search</p>
                </div>
            {% else %}
                {% if num_results %}
                    <div class="info__container info_results">
                        <h2>Search results for '{{ term }}'</h2>
                        <p>{{ num_results }} item{{ num_results|pluralize }} found</p>
                    </div>
                {% endif %}

                {% if group_filter %}
                    <div class="info__container info_results">
                        <h2>{{ group_filter }}</h2>
                        <p>{{ num_in_group }} item{{ num_in_group|pluralize }} found</p>
                    </div>
                {% endif %}

                {% if num_in_list %}
                    <div class="info__container info_results">
                        <h2>{{ name_filter|upper }}</h2>
                        <p>{{ num_in_list }} item{{ num_in_list|pluralize }} found</p>
                    </div>
                {% endif %}

                <ul class="minerals__container minerals__container_ext">
                    {% for mineral in mineral_filtered %}
                        <li class="minerals__item">
                            <a class="minerals__anchor"
                               href="{% url 'catalog:detail' pk=mineral.pk %}">{{ mineral|safe }}</a>
                        </li>
                    {% endfor %}</ul>
            {% endif %}
    </div>
{% endblock %}

catalog/templates/catalog/list.html
{% extends 'layout.html' %}

{% block boundsClass %}
    <div class="bounds">{% endblock %}
{% block importLink %}
    <div class="import">
        <a class="minerals__anchor import_button" href="{% url 'catalog:import' %}">Import data</a>
    </div>
{% endblock %}
{% block content %}
    <div class="grid-100">
            {% if not mineral_filtered %}
                <div class="info__container info_results">
                    <h2>No results found {% if term %}for '{{ term }}'{% endif %}</h2>
                    <p>Please try another search</p>
                </div>
            {% else %}
                {% if num_results %}
                    <div class="info__container info_results">
                        <h2>Search results for '{{ term }}'</h2>
                        <p>{{ num_results }} item{{ num_results|pluralize }} found</p>
                    </div>
                {% endif %}

                {% if search_term %}
                    <div class="info__container info_results">
                        <h2>{{ search_term }}</h2>
                        <p>{{ num_in_group }} item{{ num_in_group|pluralize }} found</p>
                    </div>
                {% endif %}

                {% if num_in_list %}
                    <div class="info__container info_results">
                        <h2>{{ name_filter|upper }}</h2>
                        <p>{{ num_in_list }} item{{ num_in_list|pluralize }} found</p>
                    </div>
                {% endif %}

                <ul class="minerals__container minerals__container_ext">
                    {% for mineral in mineral_filtered %}
                        <li class="minerals__item">
                            <a class="minerals__anchor mineral_single"
                               href="{% url 'catalog:detail' pk=mineral.pk %}">{{ mineral|safe }}</a>
                        </li>
                    {% endfor %}</ul>
            {% endif %}
    </div>
{% endblock %}

catalog/templates/catalog/no-data.html
{% extends 'layout.html' %}
{% block boundsClass %}
    <div class="bounds">{% endblock %}

{% block content %}
        <div class="grid-100">
    <div class="info__container">
        <h2>Welcome</h2>
        <p>The database is empty. <a class="b-link" href="{% url 'catalog:import' %}">Import data</a> to
            start.</p>
    </div>
        </div>
{% endblock %}